### ISSUE TITLE
Consider adding referrerpolicy to the background iframe

### ISSUE THREAD

**Issue by groovecoder** [mozilla/price-wise#164]
It may not be necessary, but consider adding:
```
iframe.setAttribute('referrerpolicy', 'no-referrer');
```
just to help make sure the background script's `iframe` doesn't accidentally leak a referrer.

**Comment by biancadanforth** [comment]
@groovecoder , Any idea why I wouldn't see a change in Referrer Policy in the Header (it's still `no-referrer-when-downgrade`) info despite having set the attribute for the iframe?

**Iframe attributes:**
![screen shot 2018-11-12 at 4 40 43 pm](https://user-images.githubusercontent.com/17437436/48383851-6941b280-e69c-11e8-95bb-acef7f795977.png)

**Headers for the product page request:**
![screen shot 2018-11-12 at 4 41 47 pm](https://user-images.githubusercontent.com/17437436/48383837-53cc8880-e69c-11e8-8a8e-72e14886b673.png)

**Comment by biancadanforth** [comment]
[According to bz](https://bugzilla.mozilla.org/show_bug.cgi?id=1423974#c22), setting the attribute on the iframe doesn't change the referrer policy for the document loaded into the iframe. It only covers
> the referrer policy for the load of the iframe's src

I followed up with him in IRC, and he clarified that I would verify the policy by confirming there is no `Referer` (yes, it's misspelled in the wild) request header when that document resource is fetched.

I do not see this `Referer` request header for that document in either case (as [shown above](https://github.com/mozilla/price-wise/issues/164#issuecomment-438088802)), whether `iframe.setAttribute('referrerpolicy', 'no-referrer');` is set or not.

Per aswan, because a web extension's background page is a local URL, he doesn't think adding this makes a difference.

I asked in #content in IRC to see if I can get a definitive answer from a platform person, but my suspicion is that this is not an issue in this specific situation.

**Comment by Osmose** [comment]
> I asked in #content in IRC to see if I can get a definitive answer from a platform person, but my suspicion is that this is not an issue in this specific situation.

I'm down for calling this a WONTFIX if @groovecoder is good with that.

**Comment by groovecoder** [comment]
Cool, yeah thanks for checking that the background page's request doesn't send a `Referer` value. That was the main concern, so I'm happy to WONTFIX.
