### ISSUE TITLE
The Price Wise door hanger goes blank when showing the browser window in full screen mode

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/price-wise#235]
[Affected versions]:
- Firefox Release v63.0 and up

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a Firefox profile with the latest version of the "Price Wise" add-on (8.0.0) downloaded from ([download link](https://testpilot.firefox.com/files/shopping-testpilot@mozilla.org/latest)). 
- The browser was previously resized.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the "Price Wise" button from the toolbar.
3. Press "F11" key and observe the panel.

[Expected result]:
- The panel renders correctly with full screen.

[Actual result]:
- The panel goes blank.

[Notes]:
- Here is a screen recording of the issue:

![full screen](https://user-images.githubusercontent.com/26000308/47793979-2856af00-dd28-11e8-8f9e-6aa0828eced7.gif)

**Comment by Osmose** [comment]
I'm able to replicate this with another unrelated add-on: [Emoji Cheatsheet](https://addons.mozilla.org/en-US/firefox/addon/emoji-cheatsheet/?src=homepage-collection-featured).

I've filed [bug 1510775](https://bugzilla.mozilla.org/show_bug.cgi?id=1510775) as I believe this is a bug with Firefox instead of our add-on specifically. Closing this as there isn't any more action we can take.
