### ISSUE TITLE
Door hanger expands according to item description

### ISSUE THREAD

**Issue by poubina** [mozilla/price-wise#260]
[Affected versions]:
    Firefox Release v63.0.1 and up

[Affected Platforms]:
    All Windows
    All Mac

[Prerequisites]:
    Have a Firefox profile with the latest version of the "Price Wise" add-on (11.0.0) downloaded from ([download link](https://testpilot.firefox.com/files/shopping-testpilot@mozilla.org/latest)).

[Steps to reproduce]:
    1. Open the browser with the profile from prerequisites.
    2. Navigate to http://www.amazon.com/ 
    3. Look for an Item with short description and add it to the price wise alerts list.
    4. Look for an Item with a longer description than item in step 3. and add it to the price wise alerts list.
    5. Observe width change of door hanger.

[Expected result]:
    Door hanger width doesn't change.

[Actual result]:
    Door hanger width changes.

[Notes]:
    Here is a screen recording of the issue:

![width](https://user-images.githubusercontent.com/44272078/48267322-cb868300-e410-11e8-8b2e-06521d448d33.gif)

![mac width 1](https://user-images.githubusercontent.com/44272078/48267343-dd682600-e410-11e8-9025-3b5393733525.png)

![mac width 2](https://user-images.githubusercontent.com/44272078/48267364-e9ec7e80-e410-11e8-9dde-7101d1f2028c.png)

**Comment by Osmose** [comment]
This is expected behavior; we found that when the popup is pinned to the overflow menu, the width changes from the default width our designs used. I also found that the exact width of the overflow popup isn't always consistent, so just expanding the default width didn't work either. 

The solution was to enforce a range of allowed widths based on the content and whether the popup is in the overflow menu or not.

Thanks for the issue!
