### ISSUE TITLE
Price of wrong version displayed

### ISSUE THREAD

**Issue by cshin9** [mozilla/price-wise#263]
**[Affected versions]:**

* Firefox 63.0.1

**[Affected Platforms]:**

* Windows 10

**[Prerequisites]:**

* Price Wise installed from https://testpilot.firefox.com/experiments/price-wise

**[Steps to reproduce]:**
* Open the browser and navigate to "https://www.amazon.com/dp/B01HHWSV1S"
* Click on Price Wise.
* Click "Add This Product" button and observe the behavior.

**[Expected result]:**

* The price of "Precision Cooker WI-FI + Bluetooth" is displayed.

**[Actual result]:**

* The price of "Precision Cooker Nano" is displayed.

**Comment by Osmose** [comment]
Thanks for the issue!

When I try to replicate on MacOS, I'm getting the correct prices for each product, and they're being detected as separate products correctly:

![screen shot 2018-11-12 at 2 03 40 pm](https://user-images.githubusercontent.com/193106/48377880-d9900a00-e683-11e8-82a4-67cb54145a8d.png)

Just to confirm, you're saying that if you view the link above (which highlights the Wifi + Bluetooth version by default) and add it as a product, it shows the price as $99 instead of the $129 price?

**Comment by cshin9** [comment]
That's correct.
![7qvpepg](https://user-images.githubusercontent.com/8700211/48458283-ac328180-e793-11e8-8d59-686a1a9906da.png)

**Comment by Canisaur** [comment]
I also have this issue.  Adding this 8TB HD shows the price for the 3TB version even though it shows the title for the 8TB version.

https://www.amazon.com/Seagate-Expansion-Desktop-External-STEB8000100/dp/B01HAPGEIE

**Comment by Osmose** [comment]
This appears to have been fixed in https://github.com/mozilla/price-wise/pull/275 and should be fixed in v15.0.0 which has been released.
